### PR TITLE
Added api monitoring queue.

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@tejohnso @fjvallarino please review. I have added the monitoring queue as every time storage deploys this queue is disable on rvaserver2. I was wondering if this project should also have a queue.xml. Wouldn't it be better to just keep one queue.xml on core project? @alexey-rise FYI.

Cheers.

### CODE REVIEW

**Comment by tejohnso** [comment]
@rodrigopavezi I didn't realize that a queue.xml in a module would overwrite the default app's queue.xml.  It's only in storage-server because it is used in a few unit tests that involve the queue. Without it the code under test can't find the expected storageBulkOperations queue and so it throws an error.  

We'll have to find a way around that.  We definitely don't want to manage a live queue.xml in this module.

**Comment by rodrigopavezi** [comment]
@tejohnso that is how I could use a queue.xml on a unit test. 
https://github.com/Rise-Vision/monitoring-filter/blob/master/src/test/java/com/risevision/monitoring/filter/MonitoringFilterTest.java#L71

https://github.com/Rise-Vision/monitoring-filter/tree/master/src/test/resources

cheers.

**Comment by tejohnso** [comment]
Closing this PR.  Will remove queue.xml from repo.

**Comment by alexey-rise** [comment]
@tejohnso I wonder if there is a way to check for queue.xml's presence from circle.yml and fail the build before it is deployed?

**Pull request closed without merging**
