### PR TITLE
Update RvStorageObject.objectId when moving to/restoring from Trash

### PR DESCRIPTION
**Pull request by fjvallarino**
Two classes were renamed, step which should have been part of a single commit.

@tejohnso please review

### CODE REVIEW

**Comment by fjvallarino** [comment]
@tejohnso Removed clone() call

**Comment by tejohnso** [comment]
Also need to remove "implements cloneable" and the clone method in RvStorageObject

**Comment by fjvallarino** [comment]
@tejohnso Updated

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
