### PR TITLE
Check with RvStorageObjects if file is in trash and do not return it in case it is

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso please review

### CODE REVIEW

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
I modified the endpoint so it correctly returns folders in Trash

@tejohnso please review

**Comment by tejohnso** [comment]
Why return folders in Trash?

**Comment by fjvallarino** [comment]
Because users may want to download them from storage-client (we are supposed to support download from Trash)

**Comment by tejohnso** [comment]
And that's only going to be an option when signedUrls are requested?

**Comment by fjvallarino** [comment]
@tejohnso Updated

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
