### PR TITLE
Api monitoring

### PR DESCRIPTION
**Pull request by fjvallarino**
@rodrigopavezi I followed the instructions for setting up Monitoring, but running the query on rvacore-test does not return any result (although I see CoreAPIv1 being logged). Could you check if what I did is correct? Thank you!

### CODE REVIEW

**Comment by fjvallarino** [comment]
This PR adds API monitoring for Storage. I'm not really sure we need the dependencies:override in circle.yml, since we are already calling mvn package in dependencies:post and that fetches dependencies; I copied that part from Core's monitoring setup.

@tejohnso @rodrigopavezi please review

**Comment by rodrigopavezi** [comment]
@fjvallarino I don't think the dependencies:override is needed here. I don't know why it is needed on core. It was already there so I just added the use of the config/settings.xml. If storage was working without that I believe you don't need to introduce it. cheers

**Comment by fjvallarino** [comment]
@tejohnso @rodrigopavezi updated

**Comment by rodrigopavezi** [comment]
:+1:

**Pull request merged**
