### PR TITLE
Fix #209 - Files without datastore backing objects

### LINKED ISSUE #209: Files without datastore backing objects
When requesting file contents a check is made to ensure that all returned files have an RvStorageObject.  If there is no such object, the file is not returned.   The server should also kick off a task to delete that file from GCS since it is no longer reachable and is invalid in the current system.
@fjvallarino Does the above sound right?

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu I added a verification in `getBucketItems()` to bulk delete files without datastore object.
If a file exists in Google Cloud Storage but not in datastore of requested folder or Trash datastore, the file will be queued for deletion. 

*Sorry for replacing whitespaces, I don't know what happen with my IDE.

@fjvallarino fyi

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc thinking about this some more, what would you think about:

- Logging the "to be deleted" files to BQ.
- Running this code in production but disabling the actual delete.
- Reviewing the files to be deleted after a set period of time to ensure we're not breaking anyone's content.
- Enabling the delete job once we ensure there are no conflicts.

My worry is that if we somehow delete someone's files that are actually in use this would cause some trouble and cannot be reversed.

Thoughts? Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Good point. I agree with you, it is a much safer option. 

Instead of logging to BQ, that requires a lot of effort (create a table, add server code to insert), I would suggest to just use the log output `log.info()`. We can filter and analyze with it. Thoughts? 

Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc as this is a temporary solution, the easiest would work. Sounds good re log output vs BQ logging. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I added logging for orphan files and commented the Delete task so we can re-enable it in the future. I will add a card to Debt Reduction epic for analyzing the logs and enabling Deletion. Please review. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc looks good 👍 . Thanks for the update!

**Pull request merged**
