### PR TITLE
Chore/query

### PR DESCRIPTION
**Pull request by tejohnso**
@fjvallarino **ActiveBucketFetcher**'s query needed to be changed to use time_micros instead of time_timestamp since time_timestamp is no longer part of the log table.   Please review.

I've also remove "impl" directories.  Implementations should be in the same package as the interface and mock in most cases.  Also, classes shouldn't be called XYZ**Impl** because **impl** doesn't say anything about what the implementation operates against.  Instead the pattern should be something like this:

SomethingDoer     <-interface
MockSomethingDoer    <-Mock
GoogleSomethingDoer   <- Google specific implementation
AmazonSomethingDoer  <- Implementation for Amazon or any other implementation.

### CODE REVIEW

**Comment by tejohnso** [comment]
@fjvallarino I think we have an example of not using impl with the throttling handlers.  Although one of them isn't named exactly as it should be.  
ThrottleOffendersHandler
JustLogThrottleOffendersHandler
UpdatePublicReadThrottleOffendersHandler <-This one is actually named UpdateThrottlingLockHandler

**Comment by fjvallarino** [comment]
@tejohnso The impl suffix is based on an old naming standard (I guess mostly used in Jakarta projects) for cases where only one implementation of an interface exists. For instance, in the case of SubscriptionStatusFetcher, there will be no other implementation (besides the mock), so we still have to add something to the name to differentiate it from the interface (especially if we put them in the same package).

**Comment by tejohnso** [comment]
@fjvallarino Do you see any harm in using the same practice for cases where there will be only one implementation as well as cases where there may be more than one?  For example I don't see any harm in having SubscriptionStatusFetcher, MockSubscriptionStatusFetcher and RiseVisionSubscriptionStatusFetcher.

**Comment by fjvallarino** [comment]
@tejohnso No harm in doing that, it's just not much different than using impl (since adding RiseVision does not provide more information about what it does, contrary to the case of GoogleSomethingDoer and AmazonSomethingDoer)

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
