### PR TITLE
Search files by tag endpoint

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso please review

### CODE REVIEW

**Comment by tejohnso** [comment]
So you pass in a bunch of tag names and you get back a list of all files with those tag names and the response includes the tag values, is that right?

**Comment by fjvallarino** [comment]
The response is not currently returning the tags for the file, since it's only fetching the tag names that where included in the search parameters. It's easy to include those, I did not do it because the file probably has extra tags and it could be confusing (of course, I can fetch the remaining tags, but that means performing extra queries).

**Comment by tejohnso** [comment]
Okay, so there will be a separate endpoint to get files by searching for specific name:value pairs?

**Comment by fjvallarino** [comment]
This one does that (getting files matching a given set of tagname:value constraints). It also works if you only provide the tagname (it's a side effect actually, it was not really planned).

What I was saying is it currently only returns the file name, not the associated tags.

**Comment by tejohnso** [comment]
I think the caller should get the tags back.  They may need to see them.  To check timeline details, for instance.  This way we save them from having to make a bunch of additional api calls.  d @ByronDarlison 
@EnlightenedCode 
Any preference here?

**Comment by ByronDarlison** [comment]
@tejohnso @fjvallarino sorry, somehow I missed this notification. Can we have the call for the files have an optional parameter that will by default not return the tags and if the set to true, it does? Thanks!

**Comment by fjvallarino** [comment]
Added optional parameter returnTags, used to indicate if tags associated to each file should be returned. The way data is fetched is a bit different, so I'm asking again for review.

@tejohnso please review

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
