### PR TITLE
Use storage.object.get for single file requests

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu 

I tested many different scenarios (file,folder, orphan file, not found, trash, etc) and it worked fine except for one particular case where the new call is returning a different result than previous implementation. 

Previously, requesting a file would work like a filter. For instance, if I have a file in storage called `image.png` and I request `file=imag`, the method will return that `image.png`. In the new implementation, as we are getting the file by name, the return will be empty.

The expected behavior is not specified in the docs (actually, `file` param is not listed). In my opinion, as I am specifying a particular file name, I would expect to receive an empty response.

On top of that, I can't replicate the original behavior without calling storage.objects.list. So I am willing to go for the new behavior. Any thoughts? 

To compare the results:
Previous version: https://apis-explorer.appspot.com/apis-explorer/?base=https://storage-dot-rvacore-test.appspot.com/_ah/api#p/storage/v0.01/storage.files.get?companyId=e9cb09fe-894a-4012-a358-b4688795e081&file=image&_h=22&
New version: https://apis-explorer.appspot.com/apis-explorer/?base=https://gcs-get-dot-storage-dot-rvacore-test.appspot.com/_ah/api#p/storage/v0.01/storage.files.get?companyId=e9cb09fe-894a-4012-a358-b4688795e081&file=image&_h=22&

Thanks!

### CODE REVIEW

**Comment by ezequielc** [comment]
@rodrigopavezi As Content could be affected, could you give your thoughts on the above? 
I want to make sure that the changes will not impact current behavior of widgets. 
Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc code looks good 👍 . Regarding the partial filename search, if it's not used anywhere I think we are good to go. 

Thanks.

**Comment by rodrigopavezi** [comment]
@ezequielc I looked at the rise storage component and it is calling the api with the full name of the file. @donnapep @stulees do you see any issue with this change?
cheers

**Comment by stulees** [comment]
@ezequielc @rodrigopavezi I don't see any issues, thanks.

**Comment by ezequielc** [comment]
Thanks @alex-deaconu @rodrigopavezi and @stulees

**Pull request merged**
