### PR TITLE
Exempted referer

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu Please review. 
It worked in my tests, but as you mentioned I used Rise Vision company, so I will try to test with another company before merging. Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc looks good. However, I would suggest modifying your query to return an `apps referrer` string rather than `exempted referrer`. This is more general, in terms of knowing the source of the referrer, and also it allows us to add more exemptions from different referrers.

For example, I think `rva referrer` should be exempt as well. Thoughts? 

Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Makes sense. I'll change it. Thanks

**Comment by ezequielc** [comment]
@alex-deaconu Please review. I have finally been able to test it. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc looks good :+1: . Thanks for updating.

**Pull request merged**
