### PR TITLE
Chore/queue protect

### PR DESCRIPTION
**Pull request by tejohnso**
Fails the circle post dependency check if queue.xml somehow ends up in the main source tree.
@alexey-rise Please review.

### CODE REVIEW

**Comment by alexey-rise** [comment]
:+1: looks good. 

@stevesherrie I think the Store server's circle.yml should have this as well.

**Comment by stevesherrie** [comment]
@alexey-rise I've been following along, and I agree :) I'll see if I can slip it in shortly.

**Comment by ByronDarlison** [comment]
@stevesherrie can you add a card to the queue for this, in the next up. Thanks!

**Comment by stevesherrie** [comment]
@ByronDarlison Will do.

**Pull request merged**
